# Generated by Django 4.2.2 on 2023-06-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('st', 'Учусь'), ('wk', 'Работаю'), ('st', 'Туплю'), ('st', 'Мамкин миллиардер'), ('st', 'Мамин бродяга, Папин симпотяга')], max_length=50)),
                ('salary', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
